export const types = {
  GET_LIST_USER: 'GET_LIST_USER',
  GET_DETAIL_USER: 'GET_DETAIL_USER',

  UPDATE_DETAIL_USER: 'UPDATE_DETAIL_USER',
  UPDATE_LIST_USER: 'UPDATE_LIST_USER',
  UPDATE_LIST_USER_RESET: 'UPDATE_LIST_USER_RESET',

  GET_LOGIN: 'GET_LOGIN',
  INSERT_USER: 'INSERT_USER',
  UPDATE_USER: 'UPDATE_USER',

  USER_SUCCESS: 'USER_SUCCESS',
  USER_FAILURE: 'USER_FAILURE',
  USER_RESET: 'USER_RESET',
};
